DROP DATABASE encryptor;
CREATE DATABASE encryptor WITH ENCODING 'UTF8';
\c encryptor;
CREATE TABLE users (id SERIAL PRIMARY KEY, username VARCHAR(255) NOT NULL, password VARCHAR(255), key TEXT NOT NULL);