DROP DATABASE encryptor;
CREATE DATABASE encryptor WITH ENCODING 'UTF8';
\c encryptor;
CREATE TABLE users (id SERIAL PRIMARY KEY, name TEXT NOT NULL, password TEXT NOT NULL, key TEXT NOT NULL);
CREATE TABLE messages (id SERIAL PRIMARY KEY, recipient TEXT NOT NULL, content TEXT NOT NULL, date TIMESTAMP NOT NULL DEFAULT NOW());